modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/trikzon/transparent/issues"
license = "MIT"

[[mods]]
modId = "transparent"
version = "${version}"
displayName = "Transparent"
#updateJSONURL = ""
displayURL = "https://github.com/trikzon/transparent"
#credits = ""
authors = "Trikzon"
description = '''
Allows resource packs to make entities support transparency.
'''
#logoFile = ""

[[dependencies.transparent]]
modId = "forge"
mandatory = true
versionRange = "31"
ordering = "NONE"
side = "BOTH"

[[dependencies.transparent]]
modId = "minecraft"
mandatory = true
versionRange = "1.15.*"
ordering = "NONE"
side = "BOTH"