# IMPORTANT:
# Every field listed here must be added to the expandProps map in
# buildSrc/src/main/goovy/multiloader-common.gradle.

# Project
group=com.diontryban.transparent
java_version=21

# Mod
mod_id=transparent
mod_name=Transparent
mod_author=Trikzon
version=21.0.0
license=LGPL-3.0-or-later
credits=
description=Allow resource packs to make certain entities support transparency.

# Common
minecraft_version=1.21
minecraft_version_range=[1.21, 1.22)
neoform_version=1.21-20240613.152323
parchment_minecraft_version=1.21
parchment_version=2024.11.10
ash_version=21.0.4

# Fabric
fabric_version=0.102.0+1.21
fabric_loader_version=0.16.14
modmenu_version=11.0.3

# NeoForge
neoforge_version=21.0.167
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
